# Generated by Django 6.0.3 on 2026-05-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='created_at',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
