# Generated by Django 6.0.3 on 2026-05-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_friendrequest_created_at_friendrequest_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
